<?php

/**
 * @file
 * WebService Content module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\xtc\XtendedContent\API\Config;

/**
 * Implements hook_help().
 */
function xtcsearch_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.xtcsearch':
      return Config::getHelp('xtcsearch');
  }
}

/**
 * Implements hook_theme().

 */
function xtcsearch_theme($existing, $type, $theme, $path) {
  return [
    'xtc_search_item' => [
      'variables' => [
        'response' => null,
      ],
      'template' => 'xtc-search-item',
    ],
    'xtc_search_form' => [
      'variables' => [
        'response' => null,
        'form' => null,
      ],
      'template' => 'xtc-search',
    ],
    'xtc_search_title_form' => [
      'variables' => [
        'response' => null,
        'form' => null,
      ],
      'template' => 'xtc-search-title',
    ],
  ];
}
