<?php

/**
 * @file
 * WebService Content module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function xtcsearch_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.xtcsearch':
      $variables = [
        ':xtcsearch' => Url::fromRoute('help.page', ['name' => 'xtcsearch'])->toString(),
      ];

      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The <a href=":xtcsearch">WebService Content</a> module provide features to pull and push indexes between Drupal instance and ElasticeSearch remote servers.', $variables) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<p>' . t('[to be completed]') . '</p>';

      return $output;
  }
}

/**
 * Implements hook_theme().

 */
function xtcsearch_theme($existing, $type, $theme, $path) {
  return [
    'xtc_search_item' => [
      'variables' => [
        'response' => null,
      ],
      'template' => 'xtc-search-item',
    ],
    'xtc_search_form' => [
      'variables' => [
        'response' => null,
        'form' => null,
      ],
      'template' => 'xtc-search',
    ],
  ];
}
